# -*- coding: utf-8 -*-
SITE = dict(
    name="Lutz Fences",
    brand="76 FENCE",
    full_brand="76 FENCE Lutz",
    phone="813-669-4511",
    phone_tel="+18136694511",
    # Parent company — Lutz and Tampa are both locations of 76 FENCE Tampa
    parent="76 FENCE Tampa",
    tampa_phone="813-669-4555",
    tampa_phone_tel="+18136694555",
    email="tampa@76fence.com",
    city="Lutz",
    state="FL",
    state_full="Florida",
    region="Tampa Bay",
    domain="lutzfences.com",
    fb="https://www.facebook.com/76FenceLutz",
    ig="https://www.instagram.com/76fencelutz",
    google="https://g.page/r/CYR3FNx_NQIDEAI",
    year="2026",
    formspree="https://formspree.io/f/xaenwbav",
    map_embed="https://www.google.com/maps?q=76+Fence+Tampa,+Lutz,+FL&output=embed",
)

# (Display Name, slug)
TOWNS = [
    ("Lutz", "lutz"), ("Land O' Lakes", "land-o-lakes"), ("Land O' Lakes North", "land-o-lakes-north"),
    ("Odessa", "odessa"), ("Wesley Chapel", "wesley-chapel"), ("New Port Richey", "new-port-richey"),
    ("New Port Richey East", "new-port-richey-east"), ("Port Richey", "port-richey"),
    ("Zephyrhills", "zephyrhills"), ("Dade City", "dade-city"), ("San Antonio", "san-antonio"),
    ("Saint Leo", "saint-leo"), ("Spring Hill", "spring-hill"), ("Spring Hill South", "spring-hill-south"),
    ("Brooksville", "brooksville"), ("Brooksville East", "brooksville-east"), ("Ridge Manor", "ridge-manor"),
    ("Nobleton", "nobleton"), ("Masaryktown", "masaryktown"), ("Shady Hills", "shady-hills"),
    ("Hudson", "hudson"), ("Hudson South", "hudson-south"), ("Gulf Harbors", "gulf-harbors"),
    ("Angeline", "angeline"), ("Beacon Woods", "beacon-woods"), ("Bexley", "bexley"),
    ("Chapel Crossings", "chapel-crossings"), ("Connerton", "connerton"), ("Epperson Lagoon", "epperson-lagoon"),
    ("Estancia", "estancia"), ("Lake Bernadette", "lake-bernadette"), ("Lake Jovita", "lake-jovita"),
    ("Lake Padgett Estates", "lake-padgett-estates"), ("Lexington Oaks", "lexington-oaks"),
    ("Meadow Pointe", "meadow-pointe"), ("Oakstead", "oakstead"), ("Richland", "richland"),
    ("Saddlebrook", "saddlebrook"), ("Saint Joseph", "saint-joseph"), ("Seven Hills", "seven-hills"),
    ("Seven Oaks", "seven-oaks"), ("Southern Hills", "southern-hills"), ("Southport Springs", "southport-springs"),
    ("Sterling Hill", "sterling-hill"), ("Union Park", "union-park"), ("WaterGrass", "watergrass"),
    ("Wilderness Lake Preserve", "wilderness-lake-preserve"), ("Wiregrass Ranch", "wiregrass-ranch"),
]

MATERIALS = [
    dict(slug="vinyl-fence", name="Vinyl Fence", short="Vinyl",
         tagline="Vinyl fencing that never needs painting, staining, or sealing.",
         img="vinyl",
         body=[
            "Vinyl is one of the most popular fence materials we install across the Tampa Bay area, and for good reason: it never needs to be painted, stained, or sealed, it won't rot, splinter, or rust, and Florida's heat and humidity barely touch it. We install vinyl in solid-board privacy panels, semi-privacy (spaced-picket) panels, and classic picket, lattice-top, and scalloped styles, in heights from 4' to 6'.",
            "Every vinyl fence we install uses reinforced rails and posts engineered to resist sagging and warping in our heat, with color that's built into the material rather than painted on, so it won't chalk, fade, or peel in the Florida sun the way painted wood can. Popular color options include white, almond/tan, and clay.",
            "If you have a pool, vinyl is also a great fit for a code-compliant pool safety barrier — we build the gate hardware (self-closing, self-latching) to meet Florida's residential pool barrier requirements.",
         ],
         features=["No painting, staining, or sealing — ever", "Won't rot, splinter, rust, or attract termites",
                    "Reinforced rails resist sagging in Florida heat", "Privacy, semi-privacy, picket, and lattice styles",
                    "4', 5', and 6' heights available", "Pool-code-compliant gate hardware available"]),
    dict(slug="wood-fence", name="Wood Fence", short="Wood",
         tagline="Classic cedar and pressure-treated pine, built the right way.",
         img="wood",
         body=[
            "There's nothing like a wood fence for warmth and classic curb appeal, and we install both cedar and pressure-treated pine across Lutz and the surrounding communities. Pressure-treated pine is our most budget-friendly option and holds up well to Florida's climate when properly sealed; cedar offers a richer grain and natural insect resistance at a step up in price.",
            "We build wood fences in stockade (tight board-to-board), board-on-board, shadowbox, picket, horizontal, and split-rail styles, so whether you want full privacy or a more open, decorative look, we can build it. Because Florida's humidity is tough on any wood fence, we recommend staining or sealing within the first year and re-staining every 2–3 years — we offer that service too.",
            "All wood fences are set with concrete footings for stability in our sandy soil and are built to meet local wind-load expectations.",
         ],
         features=["Cedar or pressure-treated pine", "Stockade, board-on-board, shadowbox, picket, horizontal, split-rail styles",
                    "Concrete-set posts for stability", "Staining & sealing service available", "Budget-friendly option available"]),
    dict(slug="aluminum-fence", name="Aluminum Fence", short="Aluminum",
         tagline="Decorative, rust-proof, and the go-to choice for pool enclosures.",
         img="aluminum",
         body=[
            "Aluminum is a Florida favorite — it's decorative, virtually maintenance-free, and because it's rust-proof, it holds up beautifully to our humidity and coastal air without ever needing to be repainted. It's also the material most homeowners choose for pool enclosures, since open-style aluminum panels meet Florida's pool safety code while still giving you a clear view of the water.",
            "We install powder-coated aluminum in black, bronze, and white, in flat-top, spear-top, and puppy-picket (extra bottom rail for pets) styles, at 4', 5', and 6' heights. Aluminum won't warp, crack, or fade, and every panel we install carries a manufacturer warranty.",
         ],
         features=["Rust-proof, powder-coated finish", "Ideal for Florida pool safety enclosures", "Black, bronze, and white",
                    "Flat-top, spear-top, and puppy-picket styles", "Manufacturer warranty included"]),
    dict(slug="chain-link-fence", name="Chain Link Fence", short="Chain Link",
         tagline="The most budget-friendly way to secure a large property.",
         img="chain-link",
         body=[
            "Chain link is the most cost-effective fencing material we install, and it's still one of the best options when you need to enclose a large yard, dog run, or commercial lot quickly and affordably. We install galvanized chain link as well as black and green vinyl-coated chain link, which blends in far better against landscaping than bare galvanized steel.",
            "Heights typically run 4' for residential and 6'–10' for commercial and security applications, with options for privacy slats, barbed wire, and commercial-grade gate hardware including cantilever slide gates.",
         ],
         features=["Most affordable fencing material", "Galvanized or vinyl-coated (black/green)", "4' residential, 6'-10' commercial",
                    "Privacy slat inserts available", "Fast installation"]),
    dict(slug="composite-fence", name="Composite Fence", short="Composite",
         tagline="Premium, nearly maintenance-free, built to outlast wood.",
         img="composite",
         body=[
            "Composite fencing is the highest-end material we offer — a blend of wood fiber and recycled plastic that gives you the look of a rich wood fence without the rot, splintering, insect damage, or repeated staining. It's an especially good match for Florida's heat and humidity, since composite won't warp, crack, or fade the way natural wood can over time.",
            "Composite carries the longest manufacturer warranties of any material we install, and it's available in a range of wood-tone colors and privacy, semi-privacy, and horizontal styles.",
         ],
         features=["Won't rot, warp, or attract insects", "Handles Florida heat & humidity with ease", "Long manufacturer warranties",
                    "Multiple wood-tone colors", "Privacy, semi-privacy & horizontal styles"]),
    dict(slug="steel-wrought-iron-fence", name="Steel & Wrought Iron Fence", short="Steel & Wrought Iron",
         tagline="Ornamental strength for estates, pools, and commercial security.",
         img="steel",
         body=[
            "For homeowners and businesses who want a fence that makes a statement while adding real security, we install ornamental steel and wrought-iron-style fencing. It's a common choice for estate entrances, pool enclosures that need a more upscale look than standard aluminum, and commercial properties that need a serious security perimeter.",
            "All steel fencing we install is powder-coated to resist rust and corrosion in Florida's humid, salt-air climate, and can be custom-fabricated with finials, scrollwork, and matching gates.",
         ],
         features=["Powder-coated to resist rust & corrosion", "Custom fabrication & matching gates", "Estate, pool, and commercial security use",
                    "Heavy-duty for high-security applications"]),
]

STYLES = [
    dict(slug="privacy-fence", name="Privacy Fence",
         desc="Solid, tightly-fitted panels — usually vinyl, wood, or composite — built to fully block sightlines into your yard. Our most requested residential style for backyards, pools, and properties that back up to neighbors or busy roads."),
    dict(slug="semi-privacy-fence", name="Semi-Privacy Fence",
         desc="The same solid-panel look as a full privacy fence, but with small gaps (typically 1/2\" to 4\") between boards, so light and airflow get through while still screening most of the view. A popular middle ground for homeowners who want privacy without a fully closed-in feel."),
    dict(slug="horizontal-fence", name="Horizontal Fence",
         desc="A modern, high-end look built from horizontal boards or slats instead of vertical pickets. We build horizontal fences in wood, composite, and vinyl for homeowners who want a contemporary style that stands out from the typical privacy fence."),
    dict(slug="picket-fence", name="Picket Fence",
         desc="The classic front-yard fence — evenly spaced vertical pickets, usually 3'-4' tall, in wood, vinyl, or aluminum. Decorative rather than for privacy, and a great way to add curb appeal without blocking your yard from view."),
    dict(slug="split-rail-fence", name="Split Rail Fence",
         desc="An open, rustic style built from horizontal wood rails set between posts, with no pickets at all. Common for marking large property lines, farm and ranch use, or a natural look along a driveway, and often paired with wire mesh if you need to actually contain pets or livestock."),
]

COMMERCIAL = [
    dict(slug="industrial-fencing", name="Industrial Fencing",
         desc="Heavy-duty chain link and steel security fencing built for warehouses, distribution centers, utility sites, and industrial yards that need a serious perimeter — including tall heights, barbed wire top guards, and cantilever slide gates."),
    dict(slug="security-fencing", name="Security Fencing",
         desc="High fences (6'-10'+) in chain link, steel, or ornamental aluminum, designed to control access and deter intrusion at commercial properties, schools, and athletic facilities, with commercial-grade gates and access hardware."),
    dict(slug="hoa-fencing", name="HOA & Community Fencing",
         desc="Fencing for HOAs, condo associations, townhome communities, and apartment complexes — matching, code-compliant perimeter and amenity fencing installed and maintained to keep your community's board and residents happy."),
    dict(slug="dumpster-enclosures", name="Dumpster Enclosures",
         desc="Code-required screening enclosures for dumpsters and waste areas at commercial and multifamily properties, built in wood, vinyl, or chain link with privacy slats to match your property's look."),
]

OTHER_SERVICES = [
    dict(slug="fence-repair", name="Fence Repair", tagline="Leaning posts, storm damage, broken gates — we fix it.",
         body=["Fences take a beating in Florida — wind, rain, and humidity all add up. We repair leaning or rotted posts, storm-damaged panels, broken gates and hardware, and sagging rails on wood, vinyl, aluminum, and chain link fences, whether or not we installed the original fence."]),
    dict(slug="fence-staining", name="Fence Staining & Sealing", tagline="Protect your wood fence investment from Florida's climate.",
         body=["Wood fences need to be stained or sealed within the first year and re-treated every 2-3 years to hold up against Florida's sun and humidity. We pressure wash, prep, and stain or seal cedar and pressure-treated wood fences to keep them looking new and protected against rot."]),
    dict(slug="artificial-grass", name="Artificial Grass Installation", tagline="A green yard year-round, with zero irrigation or mowing.",
         body=["We install synthetic turf for backyards, pet areas, and pool decks — a great pairing with a new fence if you want a clean, low-maintenance yard without watering restrictions, brown patches, or weekly mowing."]),
    dict(slug="diy-fence", name="DIY Fence Help", tagline="Materials only, post-hole digging, or a paid consultation — your call.",
         body=["Building your own fence? We offer three ways to help without taking the whole project off your hands: material-only purchases at contractor pricing, post-hole digging as a standalone service, and a paid on-site consultation where we help you plan layout, materials, and permitting before you start."]),
    dict(slug="deck-railing", name="Deck & Railing Installation", tagline="Wood, composite, and aluminum railing to match your fence.",
         body=["We install and repair deck railing in wood, composite, and aluminum — often alongside a new fence project so the materials and finish match across your whole property."]),
    dict(slug="retaining-walls", name="Retaining Wall Installation", tagline="Manage grade changes and drainage before we fence the yard.",
         body=["For yards with slope or drainage issues, we build retaining walls in block or timber to manage grade changes, often as a first step before fence installation so posts are set on stable, properly graded ground."]),
]

FAQS = [
    ("What type of fences do you install?",
     "We install just about every residential and commercial fence type — vinyl, wood, aluminum, chain link, composite, and steel/wrought iron — in privacy, semi-privacy, picket, horizontal, and split-rail styles."),
    ("What materials do you use for fence installation?",
     "We install vinyl, wood (cedar and pressure-treated pine), aluminum, chain link, composite, and steel/wrought iron, all from established manufacturers with real warranty backing."),
    ("How long does it take to install a fence?",
     "Most residential yards take 1-2 days once we're on site. Larger properties, commercial jobs, or weather delays can push that out to about a week."),
    ("Can you provide a written estimate for fence installation?",
     "Yes — we start with a free phone or on-site consultation, and once you're ready to move forward we confirm the scope, materials, and price in writing before any work begins."),
    ("Do you have any customer references or reviews?",
     "We do — check out our latest reviews on Google and Facebook, linked in the footer of every page."),
    ("Is your company licensed and insured?",
     "Yes. 76 FENCE is licensed, bonded, and insured in all 50 states."),
    ("What is your experience with fence installation?",
     "Our team brings decades of combined fence installation experience, backed by the training, purchasing power, and manufacturer relationships of the 76 FENCE network."),
    ("Do you obtain the necessary permits for fence installation?",
     "In most cases, yes — we handle the local permitting process on your behalf as part of the installation price."),
    ("How do you handle repairs or maintenance after installation?",
     "Workmanship issues on your installation are covered by our <a href=\"warranty.html\">76-week workmanship warranty</a>. Beyond that, we handle fence repair, re-staining, and general maintenance long after your original installation — you don't have to go find a different contractor later."),
    ("What is your warranty or guarantee for fence installation?",
     "Every fence we install is backed by our <a href=\"warranty.html\">76-Week Limited Workmanship Warranty</a>. If there's a defect in our installation or assembly within 76 weeks of your installation date, we'll inspect it and make it right at no charge. Materials are covered separately by the manufacturer's warranty."),
    ("Do you offer financing or payment options?",
     "Yes — we offer flexible financing options in addition to standard payment terms."),
    ("How do you handle issues or disputes after installation?",
     "If anything comes up, we address it directly with a site visit — we'd rather fix it than argue about it."),
    ("Can you provide a timeline for fence installation?",
     "Installation itself typically runs 1-2 days weather permitting; total time from signed estimate to installation is usually a few weeks, depending on permitting and material lead times."),
    ("Do you offer customization options?",
     "Absolutely — send us a photo of what you have in mind and we'll help make it happen."),
    ("How do you ensure the fence is compliant with local codes?",
     "We pull the required permit with your local jurisdiction and build to code, including Florida's pool safety barrier requirements when a pool is involved."),
    ("Do you do free estimates?",
     "Yes, every estimate is free with no obligation."),
    ("What is the cheapest fence to install?",
     "Galvanized chain link and pressure-treated pine are typically the most affordable options."),
    ("How much does it cost to fence a property?",
     "It depends on linear footage, material, height, gates, and site conditions — get a free quote for an exact number specific to your property."),
    ("Is wood or vinyl fence better?",
     "It depends on your priorities. Wood gives you a classic, dense, natural look; vinyl wins on low maintenance and long-term durability, especially in Florida's climate."),
    ("What does PVC/vinyl fencing look like?",
     "Vinyl fencing has a smooth, painted look without visible grain — it's available in solid colors like white, almond/tan, and clay."),
    ("What time of year is cheapest to install a fence?",
     "Early spring and fall tend to offer the best pricing and scheduling availability, ahead of and after the busiest summer season."),
    ("What type of fence adds the most value?",
     "A high-quality vinyl, composite, or well-maintained stained cedar fence tends to add the most resale value."),
    ("Do I need a permit to build a fence around my house in Florida?",
     "Most Florida municipalities and counties require a fence permit, and if you have a pool, your fence or gate also has to meet Florida's pool safety barrier code. We handle that process for you."),
    ("Will my fence hold up to Florida storms and wind?",
     "We set posts in concrete to the depth needed for the material and height, and can talk through wind-rated material and design choices for storm-prone properties."),
    ("Do I need HOA approval before installing a fence?",
     "Many communities in the Lutz/Tampa Bay area require HOA approval before installation — we're happy to help prepare what your HOA needs to review."),
]

PRICING_TABLE = {
    "Average Yard (150–250 linear ft)": {
        "Chain Link": "$6,000 – $10,000",
        "Aluminum": "$8,000 – $14,000",
        "Wood": "$9,000 – $14,000",
        "Vinyl": "$10,000 – $17,000",
    },
    "Larger Yard (250–400 linear ft)": {
        "Chain Link": "$10,000 – $16,000",
        "Aluminum": "$14,000 – $20,000",
        "Wood": "$14,000 – $22,000",
        "Vinyl": "$17,000 – $26,000",
    },
    "Very Large Yard (400+ linear ft)": {
        "Chain Link": "$22,000+",
        "Aluminum": "$20,000+",
        "Wood": "$22,000+",
        "Vinyl": "$26,000+",
    },
}

# 76-Week Limited Workmanship Warranty — the single source for every warranty
# mention on the site. Edit here and re-run build_all.py.
WARRANTY = dict(
    issuer="76 FENCE Tampa",  # the company that issues and honors the warranty
    weeks=76,
    name="76-Week Limited Workmanship Warranty",
    short="76-Week Workmanship Warranty",
    approx="about 17&frac12; months",
    tagline="We stand behind our work.",
    covered=[
        "Posts that were improperly set, aligned, or installed",
        "Panels, rails, pickets, and fence fabric that were improperly assembled or attached",
        "Gates that were improperly hung, including hinges and latches we installed",
        "Fasteners and other components installed by 76 FENCE Tampa",
    ],
    not_covered=[
        "Normal wear and tear",
        "Storms, hurricanes, high winds, flooding, lightning, or other weather events",
        "Soil settlement, erosion, ground movement, or drainage conditions",
        "Trees, roots, vegetation, animals, insects, vehicles, lawn equipment, or accidents",
        "Improper maintenance or misuse",
        "Alterations, repairs, adjustments, or modifications by anyone other than 76 FENCE Tampa",
        "Material conditions such as fading, rust, warping, cracking, or splitting (see manufacturer warranty)",
    ],
    terms=[
        ("Coverage Period",
         "76 FENCE Tampa warrants the workmanship and assembly of your fence installation for 76 weeks from the installation completion date, as recorded in 76 FENCE Tampa's records."),
        ("Eligibility",
         "This warranty is conditioned on payment in full of the contract price for the installation. 76 FENCE Tampa is not obligated to perform warranty service on any project with an outstanding balance. The warranty period begins on the installation completion date regardless of when payment is received, and is not extended by any delay in payment."),
        ("What Is Covered",
         "This warranty covers defects resulting directly from the workmanship or installation performed by 76 FENCE Tampa. Covered workmanship may include improper installation or assembly of posts, panels, rails, pickets, fence fabric, gates, hinges, latches, fasteners, and other components installed by 76 FENCE Tampa."),
        ("Our Remedy",
         "If a covered workmanship defect is identified during the warranty period, 76 FENCE Tampa will inspect the affected area and, if determined to be covered by this warranty, repair or correct the workmanship at no charge to the customer."),
        ("Material &amp; Product Warranties",
         "This warranty applies only to workmanship and installation performed by 76 FENCE Tampa. Product defects, deterioration, fading, discoloration, corrosion, rust, warping, cracking, splitting, shrinking, expansion, or other material-related conditions are not covered by the 76 FENCE Tampa workmanship warranty. Such issues may be covered separately by the product manufacturer's warranty, where applicable."),
        ("Exclusions",
         "This warranty does not cover damage or changes resulting from normal wear and tear; storms, hurricanes, high winds, flooding, lightning, or other weather events; soil settlement, erosion, ground movement, or drainage conditions; trees, roots, vegetation, animals, insects, vehicles, lawn equipment, or accidents; improper maintenance or misuse; or alterations, repairs, adjustments, or modifications performed by anyone other than 76 FENCE Tampa."),
        ("Scope",
         "This warranty applies to the original installation performed by 76 FENCE Tampa at the original installation property and is limited to correcting covered workmanship defects."),
        ("Requesting Warranty Service",
         "To request warranty service, contact 76 FENCE Tampa and provide the installation address and a description or photographs of the issue. 76 FENCE Tampa will evaluate the condition to determine whether it is covered under this workmanship warranty."),
    ],
)
