# -*- coding: utf-8 -*-
"""brooksvillefence.com — its own look and its own words.

Voice: practical, rural-friendly, plain-spoken. Audience: Hernando County homeowners on larger or
sloped lots, small farms, and Spring Hill subdivisions. Keep every claim factual (no invented
reviews, years in business, or statistics); licensing/insurance wording must match sites.py."""

THEME = dict(
    body_class="theme-rugged",
    fonts_href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@600;700;800&family=Source+Sans+3:wght@400;600;700&display=swap",
    vars={
        "--font-head": "'Roboto Slab', Georgia, serif",
        "--font-body": "'Source Sans 3', -apple-system, 'Segoe UI', Roboto, Arial, sans-serif",
        "--head-weight": "700",
        "--btn-radius": "6px",
        "--accent": "#2f5d3a",
        "--accent-dark": "#1e3b26",
        "--eyebrow": "#2f5d3a",
        "--alt-bg": "#f5f2eb",
        "--hero-eyebrow": "#e8c36a",
        "--hero-bg": "linear-gradient(120deg, #1e3b26 0%, #13263a 100%)",
        "--section-pad": "72px",
    },
    hero="image",
    hero_image="materials/split-rail-fence.jpg",
    home_sections=[
        ("local", False), ("services", True), ("process", False), ("why", True), ("styles", False),
        ("warranty", True), ("gallery", False), ("pricing", True), ("areas", False), ("faq", True),
    ],
    detail_layout="guide",
    town_sections=["intro", "faq", "materials", "nearby"],
)

LICENSED = "Licensed in Hillsborough, Pasco, and Hernando counties and fully insured with general liability and workers' compensation coverage."

CONTENT = {
    "labels": {"estimate": "Get a Free Estimate", "glance": "Quick Facts", "or_call": "or call", "read_more": "Details &rarr;",
               "related_materials": "Compare Other Materials", "related_styles": "Other Styles That Work Here",
               "related_commercial": "More Commercial Work", "related_other": "Other Ways We Help"},
    "footer_about": "Brooksville Fence (brooksvillefence.com) is the Hernando County website of 76 FENCE Tampa, building residential, farm, and commercial fencing across Brooksville, Spring Hill, and the surrounding area.",
    "cta": {"title": "Let's Walk Your Property Line", "sub": "Free on-site estimates across Brooksville and Hernando County — no pressure, no obligation."},
    "warranty_box": {
        "eyebrow": "Our Promise",
        "title": "Every Fence Carries Our 76-Week Workmanship Warranty",
        "text": "If something we built isn't right — a post we set, a panel we hung, a gate we installed on {context} — within {weeks} weeks ({approx}) of your installation date, we come back and fix it at no charge. The {issuer} {name} covers our work; the manufacturer covers the materials.",
    },

    # ------------------------------------------------------------------ homepage
    "home": {
        "meta_title": "Brooksville Fence Company | 76 FENCE Tampa — Hernando County Fencing",
        "meta_description": "Fence installation in Brooksville, Spring Hill, and Hernando County: farm and split rail, privacy, pool, and security fencing. Licensed and insured. Free on-site estimates — call 813-669-4555.",
        "hero": {
            "eyebrow": "Brooksville Fence · 76 FENCE Tampa",
            "h1": "Fences Built for Brooksville Land",
            "lead": "From Spring Hill backyards to acreage along the Brooksville Ridge, we build privacy, farm, pool, and security fencing that fits the ground it stands on.",
            "cta": "Schedule a Free Estimate",
            "badges": ["Licensed &amp; Fully Insured", "Free On-Site Estimates",
                       '<a href="warranty.html" style="color:inherit">76-Week Workmanship Warranty</a>', "Owner-Operated"],
        },
        "local": {
            "eyebrow": "Know the Ground",
            "title": "What Makes Hernando County Fencing Different",
            "intro": "Brooksville properties rarely look like a standard suburban lot. We plan for the things that change how a fence goes in.",
            "cards": [
                ("Longer Runs", "Acreage and rural lots mean hundreds of feet of fence line. We help you put the budget where it matters — sturdier material by the house, simpler fencing along the back line."),
                ("Hills &amp; Slopes", "On rolling ground we step or rack panels to follow the grade, so you don't end up with gaps underneath or a jagged top line."),
                ("Rock Near the Surface", "Some Brooksville lots hit rock a short way down. We check on site and plan post depth and footings before we quote, not on install day."),
                ("Animals &amp; Equipment", "Wide drive gates for trucks and mowers, and wire-mesh backing on split rail to keep dogs and small animals where they belong."),
            ],
        },
        "services": {
            "eyebrow": "Materials",
            "title": "Choose What Fits Your Property",
            "intro": "Every material has a job it does best. Here's where each one earns its keep in Hernando County.",
            "more": "How it works on your lot &rarr;",
        },
        "process": {
            "eyebrow": "How It Works",
            "title": "From First Call to Final Walkthrough",
            "intro": "No surprises, no guesswork — here's what to expect once you reach out.",
            "steps": [
                ("Walk the Line", "We meet you on the property, walk the fence line, and look at slope, soil, gates, and access."),
                ("Written Quote", "You get a written price with the material, height, gates, and layout spelled out — before any work starts."),
                ("Permits &amp; Prep", "We check whether your address needs a permit or HOA sign-off and take care of it, then schedule your install."),
                ("Build &amp; Walkthrough", "Our crew sets posts, builds the fence, cleans up, and walks it with you before we call it done."),
            ],
        },
        "why": {
            "eyebrow": "Why Us",
            "title": "A Local Team You Can Actually Reach",
            "intro": "Brooksville Fence is part of 76 FENCE Tampa, owned and run by Tom &amp; Kate Donnelly. When you call, you get the people responsible for your fence.",
            "items": [
                ("Licensed &amp; Insured", LICENSED),
                ("Free, Honest Estimates", "We'll tell you what your property actually needs — and when a cheaper option will do the job just as well."),
                ("76-Week Workmanship Warranty", "Our installation is covered by a <a href=\"warranty.html\">76-Week Limited Workmanship Warranty</a>, on top of the manufacturer's material warranty."),
                ("Owner-Operated", "Tom and Kate run the business themselves, and your project has a real point of contact from quote to cleanup."),
                ("Permits Handled", "City of Brooksville, unincorporated Hernando County, or Pasco — we check the rules for your address and file what's needed."),
                ("Financing Available", "Ask about financing options if you'd like to spread the cost of a larger project."),
            ],
        },
        "styles": {
            "eyebrow": "Styles",
            "title": "Popular Looks Around Brooksville",
            "intro": "Pick the style first, then we'll match it to the right material for your budget.",
            "more": "Explore this style &rarr;",
        },
        "gallery": {
            "eyebrow": "Fence Types",
            "title": "Fence Types We Install",
            "intro": "A quick look at the materials and styles we build most often. Tap any photo for details.",
            "button": "See Every Fence Type",
            "tiles": [
                ("Split Rail &amp; Farm", "split-rail", "split-rail-fence.html"), ("Wood Privacy", "wood", "wood-fence.html"),
                ("Vinyl Privacy", "vinyl", "vinyl-fence.html"), ("Aluminum Pool Fence", "aluminum", "aluminum-fence.html"),
                ("Chain Link", "chain-link", "chain-link-fence.html"), ("Picket", "picket", "picket-fence.html"),
                ("Steel &amp; Ornamental", "steel", "steel-wrought-iron-fence.html"), ("Commercial Security", "security", "security-fencing.html"),
            ],
        },
        "pricing": {
            "eyebrow": "Budgeting",
            "title": "Ballpark Fence Costs",
            "intro": "Longer rural runs change the math, so use these as a starting point. We'll give you an exact, written number after we see the property.",
            "button": "Read the Pricing Guide",
        },
        "areas": {
            "eyebrow": "Where We Work",
            "title": "Brooksville, Spring Hill &amp; Surrounding Towns",
            "intro": "We work throughout Hernando County and into north Pasco. If you're nearby and don't see your town, call us anyway.",
        },
        "faq": {"eyebrow": "Questions", "title": "Common Questions from Brooksville Owners"},
    },

    # ------------------------------------------------------------------ about
    "about": {
        "title": "The Team Behind Brooksville Fence",
        "lead": "Brooksville Fence is the Hernando County arm of 76 FENCE Tampa — owner-operated by Tom &amp; Kate Donnelly.",
        "story_eyebrow": "Who We Are",
        "story_title": "Owner-Run, and Accountable for Every Post",
        "story": [
            "76 FENCE Tampa is a locally owned 76 FENCE location run by Tom &amp; Kate Donnelly. Brooksville Fence is how we serve Hernando County: the same team, the same standards, and the same warranty, focused on Brooksville, Spring Hill, and the towns around them.",
            "We started out building fences in the Tampa Bay suburbs, and a lot of what we build up here is different — longer runs, sloped ground, farm gates, and properties where the fence has to hold animals as well as look good. We plan each job on site, because a quote from a template can't see a hill or a buried rock.",
            "Being part of the national 76 FENCE network gives us manufacturer relationships and training we couldn't get on our own. Being owner-operated means you're never passed around — the people who quote your fence are the people who answer for it.",
        ],
        "owners_eyebrow": "Owners",
        "owners_title": "Tom &amp; Kate Donnelly",
        "tom": "Tom spent more than 20 years in information technology for the finance and banking industries, as a principal engineer and as a leader of global teams. He runs 76 FENCE Tampa with the same focus on doing things carefully and communicating clearly, and he's out on properties across Hernando County meeting customers and planning jobs.",
        "kate": "Kate spent more than 20 years as an intelligence analyst for the federal government and holds a master's degree. She brings that same attention to detail to scheduling, permits, and follow-through, so every Brooksville-area project is organized from the first call to the final walkthrough.",
        "cta_title": "Talk to the Owners",
        "cta_sub": "Call or send us a note — Tom or Kate will make sure your project gets the attention it needs.",
        "meta": "Meet Tom and Kate Donnelly, owners of 76 FENCE Tampa and Brooksville Fence, serving Brooksville, Spring Hill, and Hernando County.",
    },
    "areas": {
        "title": "Fencing Across Hernando County",
        "lead": "Brooksville Fence installs and repairs fencing in Brooksville, Spring Hill, and the rural communities around them.",
        "h2": "Towns We Serve",
        "intro": "Pick your town for local details, or call us — we travel throughout Hernando County and into north Pasco.",
    },
    "contact": {
        "side_html": "<div class=\"divider\"></div><h3>What Happens Next</h3><ol><li>We call or text to set a time that works for you.</li><li>We meet you on the property and walk the fence line together.</li><li>You get a written quote with materials, layout, gates, and price.</li></ol><p>Most of our Hernando County estimates are scheduled within a few days of your request.</p>",
        "title": "Request a Free On-Site Estimate",
        "lead": "Tell us about your property and we'll set up a time to walk the fence line with you.",
    },
    "faq": {
        "title": "Brooksville Fence Questions, Answered",
        "lead": "Straight answers about permits, pricing, sloped lots, farm fencing, and what to expect.",
        "cta_title": "Don't See Your Question?",
        "cta_sub": "Call us — we're happy to talk through your property before you commit to anything.",
    },
    "faqs": [
        ("Are you licensed and insured?",
         "Yes. 76 FENCE Tampa is licensed in Hillsborough, Pasco, and Hernando counties and carries general liability and workers' compensation insurance. We can send you a certificate of insurance on request."),
        ("Do I need a permit for a fence in Brooksville or Hernando County?",
         "Many fence projects in the City of Brooksville and unincorporated Hernando County need a permit, and any fence that's part of a pool barrier has to meet Florida's pool code. We check the requirements for your address and handle the permit as part of the job."),
        ("Do you build fencing on acreage and small farms?",
         "Yes. Split rail, ranch-style wood, and wire-mesh combinations are common on larger Hernando County properties. We'll walk the line with you and plan corners, gates, and equipment access. For large-animal pasture fencing, ask us — we'll tell you honestly whether it's the right fit for our crews."),
        ("Can you install a fence on a hill or sloped yard?",
         "Yes. Depending on the material, we either step the panels down the slope or rack them to follow the ground, and we set each post to suit the terrain so the fence stays straight and secure."),
        ("What if you hit rock while digging?",
         "It happens on some Brooksville lots. We look for signs of it during the estimate and plan post depth and footings accordingly, so it doesn't turn into a surprise on install day."),
        ("How wide can you make a gate for trucks or a tractor?",
         "We build single and double drive gates in widths that fit trucks, trailers, and mowers. Tell us what needs to come through and we'll size the opening and hardware to match."),
        ("What's the most affordable way to fence a large property?",
         "Usually a mix: a more finished fence (vinyl, wood, or aluminum) near the house, and split rail with wire mesh or chain link along the back and side lines. We'll price out options so you can compare."),
        ("Which fence material holds up best in Hernando County's heat and humidity?",
         "Vinyl and aluminum need the least upkeep. Wood gives the most natural look but needs sealing or staining to last. Near the Gulf around Hernando Beach, rust-proof aluminum and vinyl are the safest choices."),
        ("How long does installation take?",
         "Most residential fences take one to two days once we're on site. Long rural runs, extra gates, or weather can stretch that out. From signed quote to install is usually a few weeks, depending on permits and materials."),
        ("Do you give written estimates?",
         "Always. After we visit, you'll get a written quote with the material, height, layout, and gates spelled out, and the estimate itself is free."),
        ("What does your warranty cover?",
         "Our <a href=\"warranty.html\">76-Week Limited Workmanship Warranty</a> covers defects in how we installed or assembled your fence — posts, panels, gates, hardware we put in. Materials are covered separately by the manufacturer's warranty."),
        ("Will my fence stand up to storms?",
         "We set posts in concrete at a depth that suits the material and height, and we can talk through wind-resistant designs. No fence is storm-proof, and storm damage isn't covered by our workmanship warranty, but a well-built fence gives you the best odds."),
        ("Do Spring Hill neighborhoods need HOA approval?",
         "Some do — many Spring Hill and Brooksville subdivisions have deed restrictions or HOA rules on height and style. We'll help you gather what your association needs before we build."),
        ("Can you build a pool fence that meets code?",
         "Yes. We build aluminum and vinyl pool barriers with self-closing, self-latching gates to meet Florida's residential pool safety requirements."),
        ("Do you remove my old fence?",
         "We can. Removing and hauling away an old fence is usually a small add-on to your quote, and we'll list it separately so you know what it costs."),
        ("Do you repair fences you didn't install?",
         "Yes. We repair leaning posts, storm-damaged sections, broken gates, and sagging rails on most fence types, whoever built them."),
        ("Do you offer financing?",
         "Yes — ask about financing options when you get your estimate."),
        ("Can I buy materials and build it myself?",
         "You can. We offer materials at contractor pricing, post-hole digging on its own, and paid planning consultations. See our <a href=\"diy-fence.html\">DIY help</a> page."),
    ],
    "gallery": {
        "label": "{cat}",
        "intro_html": "<p class=\"hub-intro\">Not sure what to call the fence you have in mind? Start here. Each photo shows a fence type we install around Brooksville — tap it for materials, heights, and where it works best on rural and suburban lots.</p>",
        "tiles": [("Split Rail", "split-rail", "split-rail-fence.html"), ("Wood Privacy", "wood", "wood-fence.html"), ("Chain Link", "chain-link", "chain-link-fence.html"), ("Vinyl Privacy", "vinyl", "vinyl-fence.html"), ("Aluminum", "aluminum", "aluminum-fence.html"), ("Picket", "picket", "picket-fence.html"), ("Steel &amp; Ornamental", "steel", "steel-wrought-iron-fence.html"), ("Horizontal", "horizontal", "horizontal-fence.html"), ("Composite", "composite", "composite-fence.html"), ("Commercial Security", "security", "security-fencing.html")],
        "title": "Fence Types We Build",
        "lead": "Browse the materials and styles we install across Brooksville and Hernando County, then tap any one for the details.",
        "meta": "See split rail, wood, vinyl, aluminum, chain link, and steel fence types installed by 76 FENCE Tampa in Brooksville and Hernando County.",
    },
    "pricing": {
        "title": "Fence Pricing for Hernando County Properties",
        "lead": "Typical ranges by material and fence length. Rural lots are often longer, so we quote every property in writing after a visit.",
        "intro_html": "<p style=\"max-width:760px\">These ranges come from typical residential installs. On acreage, the per-foot cost often drops as runs get longer — and mixing materials (a finished fence near the house, simpler fencing on the back line) can stretch your budget a long way.</p>",
        "factors": [
            ("Length of the Run", "Linear footage drives the total more than anything. Long rural lines add material and labor, but lower the cost per foot."),
            ("Ground Conditions", "Slopes, rock, and tree roots can change how posts are set. We check on site so the quote reflects your actual ground."),
            ("Gates &amp; Access", "Walk gates, double drive gates, and farm gates each add to the price depending on width and hardware."),
        ],
        "cta_title": "Get a Number for Your Property",
        "cta_sub": "We'll walk the line and send a written quote — free, and with no pressure.",
        "meta": "Typical fence prices in Brooksville and Hernando County by material and length, plus what changes the cost on rural and sloped lots.",
    },

    # ------------------------------------------------------------------ materials
    "materials_hub": {
        "title": "Fence Materials for Hernando County",
        "lead": "Every material we install, and where each one makes the most sense on Brooksville-area properties.",
        "intro": ["The right material depends on what the fence has to do — keep animals in, give you privacy, secure a pool, or just mark the line. Start with the job, then pick the material."],
    },
    "materials": {
        "vinyl-fence": {
            "tagline": "Clean, low-maintenance privacy that shrugs off Florida weather.",
            "meta": "Vinyl fence installation in Brooksville and Spring Hill: privacy, semi-privacy, and picket styles that never need painting. Free estimates from 76 FENCE Tampa.",
            "intro": ["Vinyl is the pick for homeowners who want a finished look and don't want to think about the fence again. It won't rot, it won't rust, and it never needs paint or stain — a big deal in Hernando County's heat and humidity."],
            "sections": [
                ("Where vinyl works best", ["Around the house, the pool, and the backyard, where you want privacy and a clean line. On larger properties, many owners use vinyl near the home and switch to split rail or chain link for the long back runs."]),
                ("Styles and colors", ["Solid privacy panels, semi-privacy with small gaps, picket, and lattice-top designs, typically 4 to 6 feet tall. White, tan, and clay are the most common colors, and the color runs through the material rather than being painted on."]),
                ("On sloped ground", ["Vinyl panels are usually stepped down a slope rather than angled. We plan the steps so the gaps under the fence stay small and the top line looks deliberate."]),
            ],
            "glance": ["No painting or staining", "Won't rot, splinter, or rust", "Privacy, semi-privacy &amp; picket", "4'–6' heights", "Pool-code gate hardware available"],
        },
        "wood-fence": {
            "tagline": "Warm, classic, and the most flexible material for custom layouts.",
            "meta": "Wood fence installation in Brooksville and Hernando County: cedar and pressure-treated pine privacy, board-on-board, and ranch styles.",
            "intro": ["Wood fits the look of a lot of Brooksville properties — older homes, farmhouses, and wooded lots. It's also the easiest material to adapt to odd angles and changing ground."],
            "sections": [
                ("Cedar vs. pressure-treated pine", ["Pressure-treated pine is the budget-friendly choice and holds up well when it's sealed. Cedar costs more but has a richer grain and natural resistance to insects."]),
                ("Styles we build", ["Stockade, board-on-board, shadowbox, picket, horizontal, and ranch-style rail fences. On hills, wood can be built to follow the slope smoothly."]),
                ("Keeping it looking good", ["Florida sun and humidity are hard on wood. Plan to seal or stain within the first year and every few years after — we offer <a href=\"fence-staining.html\">staining and sealing</a> too."]),
            ],
            "glance": ["Cedar or pressure-treated pine", "Easy to adapt to slopes and angles", "Privacy, ranch &amp; picket styles", "Posts set in concrete", "Staining service available"],
        },
        "aluminum-fence": {
            "tagline": "Rust-proof, open, and the go-to for pools and views.",
            "meta": "Aluminum fence installation in Brooksville, Spring Hill, and Hernando Beach — pool enclosures and decorative fencing that won't rust.",
            "intro": ["Aluminum gives you security without blocking the view, and because it can't rust, it's a smart choice anywhere near the water — including canal-front homes around Hernando Beach."],
            "sections": [
                ("Pool enclosures", ["Open aluminum panels are the most common way to build a pool barrier that meets Florida code while keeping the pool visible from the house. We install self-closing, self-latching gate hardware."]),
                ("Styles and finishes", ["Flat-top, spear-top, and puppy-picket styles (extra pickets along the bottom for small pets) in black, bronze, or white powder-coat, usually 4 to 6 feet tall."]),
                ("Following the ground", ["Many aluminum panels can be racked to follow a gentle slope, which keeps a clean line across rolling yards."]),
            ],
            "glance": ["Won't rust — good near the Gulf", "Pool-code compliant designs", "Black, bronze, or white", "Puppy-picket option for pets", "Manufacturer warranty"],
        },
        "chain-link-fence": {
            "tagline": "The practical way to enclose big areas, dog runs, and work yards.",
            "meta": "Chain link fence installation in Brooksville and Hernando County: galvanized and vinyl-coated chain link for yards, acreage, and commercial sites.",
            "intro": ["When you need to fence a lot of ground without spending a lot, chain link is hard to beat. It's durable, quick to install, and easy to add gates to."],
            "sections": [
                ("Galvanized or coated", ["Galvanized is the most economical. Black or green vinyl-coated chain link costs a bit more but blends into trees and pasture far better."]),
                ("Common uses around Brooksville", ["Dog runs, garden enclosures, back property lines, equipment yards, and commercial lots. Privacy slats can be added when you need screening."]),
            ],
            "glance": ["Most affordable per foot", "Galvanized or black/green coated", "4' residential, taller for commercial", "Privacy slats available", "Fast installation"],
        },
        "composite-fence": {
            "tagline": "The look of wood without the upkeep.",
            "meta": "Composite fence installation in Brooksville and Spring Hill — wood-look privacy fencing that won't rot, warp, or need staining.",
            "intro": ["Composite blends wood fiber and recycled plastic. You get a rich wood-tone look that doesn't rot, splinter, or need yearly staining."],
            "sections": [
                ("Is composite worth it?", ["It costs more up front than wood or vinyl. Owners who choose it usually plan to stay in the home a long time and want a premium look without maintenance."]),
                ("Styles", ["Privacy, semi-privacy, and horizontal designs in several wood-tone colors."]),
            ],
            "glance": ["Won't rot, warp, or splinter", "No staining needed", "Wood-tone colors", "Privacy &amp; horizontal styles", "Long manufacturer warranties"],
        },
        "steel-wrought-iron-fence": {
            "tagline": "Strong, ornamental fencing for entrances, estates, and security.",
            "meta": "Steel and wrought-iron-style fence installation in Brooksville and Hernando County, including entry gates and security fencing.",
            "intro": ["Steel makes a statement at a driveway entrance and adds real security where you need it. Powder-coating protects it from rust in our humid climate."],
            "sections": [
                ("Entrances and estates", ["Ornamental steel with matching gates is a popular choice for the front of larger properties and long driveways."]),
                ("Security", ["Heavier steel fencing works for commercial sites and anywhere you need a stronger perimeter than aluminum provides."]),
            ],
            "glance": ["Powder-coated against rust", "Matching driveway gates", "Finials &amp; custom details", "Estate and security use"],
        },
    },

    # ------------------------------------------------------------------ styles
    "styles_hub": {
        "title": "Fence Styles for Brooksville Homes",
        "lead": "The look you want comes first. Here are the styles we build most, and what each one is good for.",
    },
    "styles": {
        "privacy-fence": {
            "desc": "Solid panels with no gaps — the standard for backyards, pools, and homes near neighbors or busy roads.",
            "tagline": "Full coverage for backyards, pools, and busy roads.",
            "meta": "Privacy fence installation in Brooksville and Spring Hill in vinyl, wood, and composite. Free on-site estimates from 76 FENCE Tampa.",
            "intro": ["A privacy fence blocks the view in and gives you a backyard that feels like your own. It's our most requested style in Spring Hill and Brooksville neighborhoods."],
            "sections": [
                ("Best materials", ["Vinyl for zero maintenance, wood for a natural look and flexible layouts, and composite for a premium wood look without upkeep."]),
                ("Height and rules", ["Six feet is the most common backyard height. Some neighborhoods limit height or style, and front-yard fences are usually lower — we check before we build."]),
            ],
            "glance": ["Usually 6' tall", "Vinyl, wood, or composite", "Great for pools and busy roads", "Permit &amp; HOA check included"],
        },
        "semi-privacy-fence": {
            "desc": "Boards with small gaps that let air and light through while still screening most of the view.",
            "tagline": "Screening with airflow — a softer take on privacy.",
            "meta": "Semi-privacy fence installation in Brooksville and Hernando County in vinyl, wood, and composite.",
            "intro": ["Semi-privacy fences leave small gaps between boards, so breezes get through on hot days and the yard doesn't feel closed in."],
            "sections": [("Why choose it", ["It's a good middle ground for side yards, gardens, and homes that want some screening without a solid wall. It also tends to handle wind a little better than a fully solid fence."])],
            "glance": ["Lets breeze and light through", "Softer look than full privacy", "Vinyl, wood, or composite"],
        },
        "horizontal-fence": {
            "desc": "A modern look built from horizontal boards — sharp lines that stand out from the usual privacy fence.",
            "tagline": "Clean, modern lines in wood, composite, or vinyl.",
            "meta": "Horizontal fence installation in Brooksville and Spring Hill — modern wood, composite, and vinyl designs.",
            "intro": ["Horizontal fences give a contemporary look that's become popular for patios, pool areas, and front courtyards."],
            "sections": [("Materials and build", ["We build horizontal fences in wood, composite, and vinyl. Horizontal boards need solid framing so they stay straight, and on sloped lots we plan the steps carefully to keep the lines clean."])],
            "glance": ["Modern look", "Wood, composite, or vinyl", "Great for patios and pools"],
        },
        "picket-fence": {
            "desc": "The classic front-yard fence — decorative, welcoming, and great for curb appeal.",
            "tagline": "Curb appeal for front yards and gardens.",
            "meta": "Picket fence installation in Brooksville and Hernando County in wood, vinyl, and aluminum.",
            "intro": ["A picket fence frames the front of the house without hiding it. It's a natural fit for Brooksville's older homes and farmhouse-style properties."],
            "sections": [("Uses", ["Front yards, garden beds, and keeping small pets in without blocking the view. Typically 3 to 4 feet tall in wood, vinyl, or aluminum."])],
            "glance": ["3'–4' tall", "Wood, vinyl, or aluminum", "Decorative and pet-friendly"],
        },
        "split-rail-fence": {
            "desc": "Open rails between sturdy posts — the rural look for property lines, pastures, and long driveways.",
            "tagline": "The rural classic for property lines and pastures.",
            "meta": "Split rail fence installation in Brooksville and Hernando County, with wire-mesh backing for pets and animals.",
            "intro": ["Split rail is made for Brooksville country: long property lines, driveways, and pastures where you want to mark the land without closing it in."],
            "sections": [
                ("Keeping animals in", ["On its own, split rail marks a boundary but won't hold a dog. Adding wire mesh to the inside turns it into a practical containment fence for pets and small animals."]),
                ("Cost on long runs", ["Split rail uses less material per foot than solid fencing, which makes it one of the most economical ways to fence acreage."]),
            ],
            "glance": ["Economical on long runs", "Wire-mesh backing option", "Two- or three-rail designs", "Classic rural look"],
        },
    },

    # ------------------------------------------------------------------ commercial
    "commercial_hub": {
        "title": "Commercial &amp; Agricultural Fencing",
        "lead": "Fencing for businesses, storage and equipment yards, community properties, and working land across Hernando County.",
        "intro": "We install chain link, steel, aluminum, vinyl, and wood fencing for commercial properties, from a dumpster screen to a full security perimeter with slide gates. Every commercial job gets a written scope and one point of contact from quote to completion.",
    },
    "commercial": {
        "industrial-fencing": {
            "desc": "Heavy-duty perimeter fencing for yards, warehouses, and equipment storage, including tall chain link and slide gates.",
            "tagline": "Perimeters for yards, warehouses, and equipment storage.",
            "meta": "Industrial fence installation in Brooksville and Hernando County — tall chain link, barbed-wire top guards, and cantilever slide gates.",
            "intro": ["Equipment yards, contractor lots, and warehouses need fencing that keeps people out and holds up to daily traffic through the gate."],
            "sections": [("What we install", ["Tall galvanized or coated chain link, barbed-wire top guards where allowed, and cantilever slide gates that open wide for trucks without a track on the ground."])],
            "glance": ["6'–10'+ heights", "Cantilever slide gates", "Barbed-wire top guards", "Written scope for every job"],
        },
        "security-fencing": {
            "desc": "Taller fencing and controlled gates for commercial sites, schools, and facilities that need to limit access.",
            "tagline": "Controlled access for commercial and public sites.",
            "meta": "Security fence installation in Brooksville and Hernando County in chain link, steel, and aluminum.",
            "intro": ["Security fencing is about controlling who comes in and making it obvious where the boundary is."],
            "sections": [("Options", ["Chain link for economy, steel for strength, and ornamental aluminum where appearance matters, with commercial-grade gates and hardware."])],
            "glance": ["Chain link, steel, or aluminum", "Commercial-grade gates", "Tall perimeter options"],
        },
        "hoa-fencing": {
            "desc": "Matching perimeter and amenity fencing for HOAs and deed-restricted communities.",
            "tagline": "Consistent fencing for communities and amenities.",
            "meta": "HOA and community fence installation in Spring Hill, Brooksville, and Hernando County.",
            "intro": ["Community fencing has to match, meet code, and be easy for the board to maintain. We work with managers and boards on perimeters, pool areas, and amenity spaces."],
            "sections": [("How we work with boards", ["We provide clear written proposals, product details for review, and scheduling that keeps disruption to residents low."])],
            "glance": ["Perimeter &amp; pool areas", "Board-ready proposals", "Matching materials"],
        },
        "dumpster-enclosures": {
            "desc": "Screening enclosures for dumpsters and service areas that meet local site requirements.",
            "tagline": "Clean screening for dumpsters and service areas.",
            "meta": "Dumpster enclosure installation for Brooksville and Hernando County businesses in wood, vinyl, and chain link.",
            "intro": ["Many commercial sites need their dumpsters screened from view. We build enclosures with gates wide enough for pickup trucks to service."],
            "sections": [("Materials", ["Wood, vinyl, or chain link with privacy slats, chosen to match your building and your budget."])],
            "glance": ["Wood, vinyl, or slatted chain link", "Service-width gates", "Matches your property"],
        },
    },

    # ------------------------------------------------------------------ other services
    "other": {
        "fence-repair": {
            "tagline": "Leaning posts, storm damage, and broken gates, fixed.",
            "meta": "Fence repair in Brooksville and Hernando County for wood, vinyl, aluminum, and chain link — even if we didn't build it.",
            "intro": ["Wind, rain, and time take a toll. We repair leaning or rotted posts, damaged sections, sagging rails, and gates that won't latch — on most fence types, whoever installed them."],
            "sections": [("Repair or replace?", ["If a fence is near the end of its life, we'll say so and price both options so you can decide."])],
            "glance": ["Posts, panels, rails &amp; gates", "Any installer's fence", "Honest repair-vs-replace advice"],
        },
        "fence-staining": {
            "tagline": "Protect your wood fence from sun and humidity.",
            "meta": "Fence staining and sealing in Brooksville and Hernando County for cedar and pressure-treated wood.",
            "intro": ["Unprotected wood grays, cracks, and rots faster in Florida. Cleaning and sealing or staining keeps it looking good and lasting longer."],
            "sections": [("How often", ["Seal or stain within the first year, then every few years depending on sun exposure."])],
            "glance": ["Cleaning &amp; prep", "Stain or clear sealer", "Cedar and pine"],
        },
        "artificial-grass": {
            "tagline": "Green, mud-free yards for pets and play.",
            "meta": "Artificial grass installation in Brooksville and Spring Hill for pet areas, play spaces, and pool surrounds.",
            "intro": ["Synthetic turf stays green without watering or mowing, and it's a clean option for dog runs and play areas inside a new fence."],
            "sections": [],
            "glance": ["No mowing or watering", "Pet and play areas", "Pairs with a new fence"],
        },
        "diy-fence": {
            "tagline": "Doing it yourself? We'll help with the hard parts.",
            "meta": "DIY fence help in Brooksville: contractor-priced materials, post-hole digging, and planning consultations.",
            "intro": ["If you'd rather build your own fence, we can still help: buy materials at contractor pricing, have us dig the post holes, or book a paid visit to plan layout, materials, and permits."],
            "sections": [("Why post holes matter", ["On rocky or sloped Brooksville ground, the post holes are often the hardest part of the job. Having us dig them can save you a lot of time."])],
            "glance": ["Materials at contractor pricing", "Post-hole digging only", "Paid planning visits"],
        },
        "deck-railing": {
            "tagline": "Railing that matches your fence.",
            "meta": "Deck and porch railing installation in Brooksville and Hernando County in wood, composite, and aluminum.",
            "intro": ["We install and repair deck and porch railing in wood, composite, and aluminum, often alongside a new fence so the look matches."],
            "sections": [],
            "glance": ["Wood, composite, aluminum", "Matches your fence", "Repairs too"],
        },
        "retaining-walls": {
            "tagline": "Level the ground before you fence it.",
            "meta": "Retaining wall installation in Brooksville and Hernando County for sloped yards and drainage problems.",
            "intro": ["On hilly Brooksville lots, a retaining wall can hold back soil, manage runoff, and give a fence level ground to stand on."],
            "sections": [("Walls and fences together", ["When a wall and fence go in together, we plan them as one project so the posts end up on stable, properly graded ground."])],
            "glance": ["Block or timber", "Grade and drainage control", "Planned with your fence"],
        },
    },

    # ------------------------------------------------------------------ town pages
    "towns": {
        "title": "{town} Fence Company",
        "lead": "Fence installation and repair for {town} homes, farms, and businesses — from the 76 FENCE Tampa team.",
        "materials_eyebrow": "Options",
        "materials_title": "Fence Options for {town} Properties",
        "nearby_title": "More of Hernando County",
        "faq_title": "Questions from {town} Owners",
        "cta_title": "Get a Free Estimate in {town}",
        "cta_sub": "We'll walk your property line and send a written quote.",
        "meta_title": "{town} Fence Company | Brooksville Fence by 76 FENCE Tampa",
        "meta_description": "Fence installation in {town}, FL: privacy, farm, pool, and security fencing from 76 FENCE Tampa. Licensed and insured. Free on-site estimates — call 813-669-4555.",
        "snippet_suffix": " — built for {town} lots.",
        "snippets": {
            "vinyl-fence": "Low-maintenance vinyl privacy and picket fencing",
            "wood-fence": "Cedar and pine privacy, ranch, and board-on-board fences",
            "aluminum-fence": "Rust-proof aluminum for pools and open views",
            "chain-link-fence": "Economical chain link for big yards and dog runs",
            "composite-fence": "Wood-look composite without the upkeep",
            "steel-wrought-iron-fence": "Ornamental steel for entrances and security",
        },
        "faq_picks": [1, 3, 6, 0],
        "notes": {
            "brooksville": "In and around Brooksville, we see everything from in-town lots near the historic downtown to acreage out along the Brooksville Ridge, so we quote each property on site.",
            "spring-hill": "Spring Hill is mostly established neighborhoods, and many have deed restrictions on fence height and style — we check before we quote.",
            "weeki-wachee": "Around Weeki Wachee, sandy soil and wooded lots are common, and many owners want privacy from nearby roads and neighbors.",
            "ridge-manor": "Ridge Manor properties are often larger and more rural, so split rail, ranch-style wood, and wide drive gates come up often.",
            "nobleton": "Nobleton's rural lots near the Withlacoochee area often call for long fence lines and practical farm gates.",
            "masaryktown": "Masaryktown's farm-country roots mean plenty of pasture-style and property-line fencing, alongside backyard privacy fences.",
            "hernando-beach": "Near the water in Hernando Beach, salt air is hard on steel, so rust-proof aluminum and vinyl are usually the smart choices.",
            "dade-city": "Dade City's rolling hills make slope-friendly installs important — we plan steps or racked panels to follow the ground.",
            "san-antonio": "San Antonio's mix of in-town homes and country lots means we build everything from picket fences to long rural runs.",
            "shady-hills": "Shady Hills properties tend to be larger and wooded, so chain link, split rail, and privacy fencing for the house area are all common.",
        },
    },
}
